### ISSUE TITLE
CompilationError on torchscript model profiling

### ISSUE THREAD

**Issue by nrakltx** [octoml/octoml-profile#22] opened 2023-03-28 12:30 UTC
I am attempting to profile my [TorchScript model](https://drive.google.com/drive/folders/15zw7UPElKaaKABn5cYWS-SnDWL2axPrQ?usp=share_link) using the following code
```Python
import octoml_profile
import torch

model = torch.jit.load("traced_800_1344.pt").to(device).to(float_type).eval()

@octoml_profile.accelerate
def predict(x):
    return model(x)

with octoml_profile.remote_profile():
    for _ in range(10):
        inputs = (torch.randn((1, 3, 800, 1344), dtype=float_type, device=device),)
        predict(*inputs)
```
When running it, I get the following output
```
No backends were requested, using defaults: r6i.large/torch-eager-cpu, g4dn.xlarge/torch-eager-cuda, g4dn.xlarge/torch-inductor-cuda
Profiling was enabled but no results were recorded
Traceback (most recent call last):
  File "main.py", line 108, in <module>
    octoml()
  File "main.py", line 104, in octoml
    predict(*inputs)
  File "path/to/env/lib/python3.9/site-packages/octoml_profile/dynamo.py", line 724, in decorated_func
    raise CompilationError(exception, {'details': LOGFILE})
octoml_profile.errors.CompilationError: ('TorchRuntimeError', {'details': '/tmp/octoml-profile-2023-03-28-12:12:15.log'})
```
Inside the log file is the following content
```
2023-03-28 12:12:22,192 INFO octoml_profile.client Created session with uuid 3f156753-d8d6-4d00-9aa4-3e8139b2f795
2023-03-28 12:12:22,375 ERROR octoml_profile.dynamo Traceback (most recent call last):
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1199, in run_node
    return nnmodule(*args, **kwargs)
  File "path/to/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "path/to/env/lib/python3.9/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "path/to/env/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 987, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "path/to/env/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1066, in dispatch
    args, kwargs = self.validate_and_convert_non_fake_tensors(
  File "path/to/env/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1220, in validate_and_convert_non_fake_tensors
    return tree_map_only(
  File "path/to/env/lib/python3.9/site-packages/torch/utils/_pytree.py", line 266, in tree_map_only
    return tree_map(map_only(ty)(fn), pytree)
  File "path/to/env/lib/python3.9/site-packages/torch/utils/_pytree.py", line 196, in tree_map
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "path/to/env/lib/python3.9/site-packages/torch/utils/_pytree.py", line 196, in <listcomp>
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "path/to/env/lib/python3.9/site-packages/torch/utils/_pytree.py", line 247, in inner
    return f(x)
  File "path/to/env/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1212, in validate
    raise Exception(
Exception: Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. Found in aten.equal.default(*(tensor(6), tensor(12)), **{}) 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1152, in get_fake_value
    return wrap_fake_exception(
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 808, in wrap_fake_exception
    return fn()
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1153, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1206, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_module model(*(FakeTensor(FakeTensor(..., device='meta', size=(1, 3, 800, 1344), dtype=torch.float16), cuda:0),), **{}):
Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. Found in aten.equal.default(*(tensor(6), tensor(12)), **{}) 
(scroll up for backtrace)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "path/to/env/lib/python3.9/site-packages/octoml_profile/dynamo.py", line 707, in decorated_func
    return profiling_dynamo_decorated(*args, **kwargs)
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 342, in wrapper
    return inner_fn(self, inst)
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 965, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 474, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/variables/nn_module.py", line 203, in call_function
    return wrap_fx_proxy(
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/variables/builder.py", line 754, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/variables/builder.py", line 789, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1173, in get_fake_value
    raise TorchRuntimeError() from e
torch._dynamo.exc.TorchRuntimeError: 

from user code:
   File "main.py", line 99, in predict
    return model(x)

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True


The error above may be caused by user code error in the decorated function or a bug in TorchDynamo. In the former case, please check the trace for user code error; in the latter case, please try refining the scope of @accelerate closer to model inference.

```
As I myself am not knowledgable in the inner workings of torch dynamo and torch 2.0, I'd appreciate any help solving this issue.
My environment has an NVIDIA T4, python 3.9, `torch==2.0.0`, `torchvision==0.15.1`, `octoml-profile==0.2.0`.

**Comment by haijieg** [comment] 2023-03-28 14:33
Hi @nrakltx,

Thanks for reporting the issue. I can reproduce it on my side and confirm that it is an unhandled case with torch script module. We are actively working on resolving it.

- Are you able to run with non torchscript case?
- Are you able to use `torch.compile` with your torch script module?

If you are able to run `torch.compile` on your torch script module, would you mind trying the following workaround?

```
import octoml_profile
import torch

model = torch.jit.load("traced_800_1344.pt").to(device).to(float_type).eval()
>>> model = torch.compile(model)

@octoml_profile.accelerate
def predict(x):
   return model(x)

with octoml_profile.remote_profile():
    for _ in range(10):
        inputs = (torch.randn((1, 3, 800, 1344), dtype=float_type, device=device),)
        predict(*inputs)
```

**Comment by haijieg** [comment] 2023-03-28 15:02
Btw, we have a discord channel where we can provide more timely support. Feel free to join! https://discord.gg/Quc8hSxpMe

**Comment by nrakltx** [comment] 2023-03-28 15:14
Thanks for the prompt response!
I am able to run the code with a non torchscript model indeed, as well as run `torch.compile` on the model.

As for the suggested workaround, it does not seem to work (`torch.compile` succeeds) with the logs
```
2023-03-28 15:11:41,923 INFO octoml_profile.client Created session with uuid a0cbe608-6fd3-40cd-ae71-54d9a98bd7f5
2023-03-28 15:11:41,937 ERROR octoml_profile.dynamo Traceback (most recent call last):
  File "path/to/env/lib/python3.9/site-packages/octoml_profile/dynamo.py", line 707, in decorated_func
    return profiling_dynamo_decorated(*args, **kwargs)
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/user/Mask2Former/main.py", line 116, in predict
    return model(x)
  File "path/to/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "path/to/env/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 229, in __call__
    raise RuntimeError(
RuntimeError: 

torch._dynamo.optimize is called on a non function object.
If this is a callable class, please wrap the relevant code into a function and optimize the
wrapper function.

>> class CallableClass:
>>     def __init__(self):
>>         super().__init__()
>>         self.relu = torch.nn.ReLU()
>>
>>     def __call__(self, x):
>>         return self.relu(torch.sin(x))
>>
>>     def print_hello(self):
>>         print("Hello world")
>>
>> mod = CallableClass()

If you want to optimize the __call__ function and other code, wrap that up in a function

>> def wrapper_fn(x):
>>     y = mod(x)
>>     return y.sum()

and then optimize the wrapper_fn

>> opt_wrapper_fn = torch._dynamo.optimize(wrapper_fn)


The error above may be caused by user code error in the decorated function or a bug in TorchDynamo. In the former case, please check the trace for user code error; in the latter case, please try refining the scope of @accelerate closer to model inference.
```

**Comment by haijieg** [comment] 2023-03-28 15:17
I've filed an issue to PyTorch https://github.com/pytorch/pytorch/issues/97784 to fix the root cause of this issue.

**Comment by BenHamm** [comment] 2023-03-28 16:59
@nrakltx any other feedback on this project? We'd love to know what you think!

**Comment by haijieg** [comment] 2023-04-24 17:36
Close due to inactivity.

**Closed by haijieg** 2023-04-24 17:36 UTC
